spring.application.name=backend

# H2 Database (temporary, no installation needed)
spring.datasource.url=jdbc:h2:file:./data/career_navigator
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 web console (database dekhne ke liye browser me)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080